### ISSUE TITLE
簡単なディレクトリ構成図を書く

### ISSUE THREAD

**Issue by nsuzuki7713** [haruto830/pflist-backend#12]
プロジェクトフォルダが整ったら、READMEに簡単なディレクトリ構成図を書く

下記のようイメージ？
```
├── README.md
├── app
│   ├── Dockerfile
│   ├── go.mod
│   ├── go.sum
│   ├── main.go
│   └── tmp
│       └── runner-build
├── configs
├── database
├── doc
├── docker-compose.yml
└── scripts
```

#### 参考
[簡単なディレクトリ構成図を書く
](https://qiita.com/koyo-miyamura/items/eb740ef082914796b996)

**Comment by haruto830** [comment]
記載してもらったイメージになります！
READMEに記載する際、フォルダ毎にコメントで簡単な説明つけたほうが良いですかね？

**Comment by nsuzuki7713** [comment]
フォルダ毎に説明あった方が分かりやすそうです！
