### ISSUE TITLE
DBマイグレーション調査

### ISSUE THREAD

**Issue by haruto830** [haruto830/pflist-backend#19]

**Comment by nsuzuki7713** [comment]
少し調べてみました。
[migrate](https://github.com/golang-migrate/migrate) が一番starが多かったです！

- [公式ドキュメント](https://github.com/golang-migrate/migrate)
- [golang-migrate/migrateをパッケージとしてGoから使ってみる](https://qiita.com/tanden/items/7b4fb1686a61dd5f580d)
- [Database migrations in Golang](https://lanre.wtf/blog/2019/01/02/database-migration-golang/)

**Comment by haruto830** [comment]
一応、ORMマッパーのgormにもマイグレーション機能があるようです！
ただ、カラムの変更/削除ができないようなので、migrateの方が便利そうですね🤔

- [公式ドキュメント](http://gorm.io/ja_JP/docs/migration.html)
>警告:自動マイグレーションはテーブルや不足しているカラムとインデックスのみ生成します。データ保護のため、既存のカラム型の変更や未使用のカラムの削除はしません。

**Comment by nsuzuki7713** [comment]
>ORMマッパーのgormにもマイグレーション機能があるようです！

おぉー、知らなかったです!!

>ただ、カラムの変更/削除ができないようなので、migrateの方が便利そうですね🤔

片手落ち感がありますねｗw 
migrateで試していきましょうかー

**Comment by nsuzuki7713** [comment]
#40 でmigrateで作成してみます！
