### ISSUE TITLE
Goフレームワーク調査

### ISSUE THREAD

**Issue by haruto830** [haruto830/pflist-backend#2]
https://www.jetbrains.com/research/devecosystem-2018/go/
https://github.com/mingrammer/go-web-framework-stars

**Comment by nsuzuki7713** [comment]
webフレームワークはstarの多いginとかですかね？
（違いがよく分かってないですが、、）

**Comment by haruto830** [comment]
webフレームワークは、gin で進めようと思います。

ormライブラリも、starの多いgormで対応しようと思います。
https://gorm.io/

gin + gorm でのAPI開発の情報がいくつかあり、とっかかりやすそうな印象でした。

参考URL：
[Golang フレームワーク比較](https://qiita.com/yumin/items/5de33b068ead564ebcbf)
[Golang の DB 操作 ORM をいろいろしらべてみたい](https://qiita.com/mochizukikotaro/items/b09116e0ad2d30e37098)

**Comment by nsuzuki7713** [comment]
了解です！！ではそれで行きましょう！
このissueはcloseで問題ないと思います！
