### ISSUE TITLE
DB設計の再検討

### ISSUE THREAD

**Issue by nsuzuki7713** [haruto830/pflist-backend#33]
画面に設計に伴って、DB設計を再検討する

**Comment by haruto830** [comment]
下記修正したので、ご確認お願いします🙇‍♂️

#### 修正箇所
- PORTFOLIOSテーブルに期間、状態のカラム追加
- PORTFOLIOSテーブルのURLカラムを削除し、PORTFOLIOS_URLS , URLS_CATEGORIES テーブルの追加

https://docs.google.com/spreadsheets/d/1iMfJs2HEjGA5TPjG-f6Zk9jXMCtfcMBnUZOB_DXmY8M/edit#gid=0

**Comment by nsuzuki7713** [comment]
確認しました問題ないです！！下記確認して問題なければcloseでおｋです！
- スプレットシートに今回修正した箇所を赤文字にして欲しいです！差分確認しやすいです
- ER図の更新issueの追加
- マイグレーション更新issueの追加

**Comment by nsuzuki7713** [comment]
スプレットシートはシート一枚増やしてバージョン管理していきますか？
例）
```
201900701 PORTFOLIOSテーブルに期間、状態のカラム追加
201900801 xxx更新
```

**Comment by haruto830** [comment]
ありがとうございます！　指摘いただいた箇所対応しておきます！　 

>スプレットシートはシート一枚増やしてバージョン管理していきますか？

-> そうですね、新規で更新履歴のシート追加しておきます！

**Comment by haruto830** [comment]
スプレッドシートの赤字対応とシート追加完了したので、このイシューはクローズにします
