### ISSUE TITLE
DB設計

### ISSUE THREAD

**Issue by haruto830** [haruto830/pflist-backend#4]

**Comment by haruto830** [comment]
DB設計のたたき台を作成してみました。
https://docs.google.com/spreadsheets/d/1iMfJs2HEjGA5TPjG-f6Zk9jXMCtfcMBnUZOB_DXmY8M/edit?usp=sharing

ワイヤー画像を参考に作成し、一旦以下を想定としています。
- アピールポイントの項目は、255文字以上を考慮してTEXT型にしています
（アピールポイントとは別に、ポートフォリオの概要説明欄があったほうが良いかと思いました）
- ポートフォリオ画像はDBに登録する想定にしています
- 使用技術の項目は、カンマ区切りで登録する想定にしています

お手数ですが、レビューお願い致します！

**Comment by nsuzuki7713** [comment]
ありがとうございます！！全体的に良さそですね。
何点かコメントしました。

>ポートフォリオの概要説明欄

→これはあっても良さそうですね！！

- ユーザ認証をFirebaseでする場合はuidが発行されるのでusersテーブルに追加したいです(indexも貼る)
https://firebase.google.com/docs/auth/admin/verify-id-tokens
- パスワードもFirebaseに任せる場合は必要なさそうです
- 使用技術は別テーブルにしたほうが後々分析とかでも使いやすそうです。(マスターテーブルを作りたい気持ちもある。。)
例）SKILLS

| userID | portfolioID  | skill  |
|---|---|---|
| 1  |1   |Vue   |
| 1  |1   |Typescript   | 
| 1  |2   |Ruby   |
| 1  |2   |Rails   | 
| 2  |3   |HTML   | 
- ポートフォリオ画像も複数枚許容する設計を考えるとtableを分けてもいいかもです。
例）IMAGES

| userID | portfolioID  | skill  |
|---|---|---|
| 1  |1   |xxx.png   |
| 1  |1   |yyy.png   | 
- ポートフォリオURLとGitHubURLのNULL許可はGitHubを必須にして、ポートフォリオURLは任意でもよさそうな気がしてます。

**Comment by haruto830** [comment]
レビューありがとうございます！
ご指摘いただいたところを参考に修正しました。

### 修正箇所
> ユーザ認証をFirebaseでする場合はuidが発行されるのでusersテーブルに追加したいです  

firebase使ったことなかったですが、認証/認可周りやってくれるんですね！
以下修正しました。
- firebaseで発行される一意id用のカラム(uid)の追加
- パスワードカラムの削除

> 使用技術は別テーブルにしたほうが後々分析とかでも使いやすそうです  

確かに分析を考えたら分けたほうが良さそうですね！
後々、使用技術のランキング的なものがあったら面白いと思いました！

以下修正しました。
- PORTFOLIOS_SKILLS テーブルを追加
- SKILLS_MASTERS テーブルを追加（使用技術のマスタテーブル）
  - マスタにない技術の登録処理を考える必要がありそうです。

> ポートフォリオ画像も複数枚許容する設計を考えるとtableを分けてもいいかもです。  

枚数分カラム作るより、テーブル分けたほうが良さそうですね。
以下修正しました。
- PORTFOLIOS_IMAGES テーブルを追加

> ポートフォリオURLとGitHubURLのNULL許可はGitHubを必須にして、ポートフォリオURLは任意でもよさそうな気がしてます。

- Github_URL -> 必須 
- PORTFOLIO_URL -> 任意 
- ポートフォリオの概要説明欄カラムの追加

https://docs.google.com/spreadsheets/d/1iMfJs2HEjGA5TPjG-f6Zk9jXMCtfcMBnUZOB_DXmY8M/edit?usp=sharing

**Comment by haruto830** [comment]
追加修正しました🙇‍♂️
- スキルカテゴリのマスタテーブル（SKILL_CATEGORIES）の追加
- いいね履歴テーブルの追加

ちょっとテーブル数増えてきたので、別途PlantUMLでER図作成します！

**Comment by nsuzuki7713** [comment]
良さそうですね！！最初はこれでいきましょう！

**Comment by haruto830** [comment]
ありがとうございます！　では、一先ずはこの構成でお願いします！
このイシューはクローズします
