### ISSUE TITLE
DBにテストデータを入れたい

### ISSUE THREAD

**Issue by nsuzuki7713** [haruto830/pflist-backend#43]
開発するにあたってテーブルにデータを入れておきたい。
script文を作成すればいい？

**Comment by haruto830** [comment]
SQLファイルがあれば、大丈夫そうです！　DBコンテナにはいる必要がありそうですが。。
参考：[docker-composeのmysqlコンテナでsqlファイルを実行する方法](https://qiita.com/hekizi/items/ba8f4a7d512e9e062671)
