### ISSUE TITLE
プロジェクト構成の検討

### ISSUE THREAD

**Issue by haruto830** [haruto830/pflist-backend#6]
バックエンド側のプロジェクト構成を検討する

**Comment by haruto830** [comment]
公式ではないですが、標準的なレイアウトがある模様。
（k8s、prometeusの構成はこれに近いらしいです）
https://techdo.mediado.jp/entry/2019/01/18/112503

ただ、フォルダ数が多く複雑な印象なので、
これをベースに不要なフォルダを削っていくのが良さそう？

**Comment by nsuzuki7713** [comment]
テンプレート的なので作ってみて、必要無いところは削るでも良さそうですよね。
まずは動かせる所まで行きたいですね

**Comment by haruto830** [comment]
そうですね、一旦標準パッケージを参考にして作成してみます！

**Comment by haruto830** [comment]
とりあえず、標準を参考にテンプレート的な感じで作成してみました。
初回だったので直接masterにpushしています。
